export default function AboutPage() {
  return (
    <article className="prose prose-sm max-w-none text-[color:var(--color-ink)]">
      <h1 className="text-2xl font-bold text-[color:var(--color-brand)]">About IsItSmut</h1>
      <p>
        IsItSmut is a free tool that looks up books, movies, and TV shows and tells you, in five seconds, whether they contain sexual content — and how much.
      </p>
      <p>
        Ratings are generated by an AI model that reads your query, identifies the work, and rates it on a 1–10 scale based on the frequency and explicitness of sexual content. Results are cached so the same lookup always returns the same answer.
      </p>
      <p>
        Built because you should be able to look at a stranger reading a book on the subway and know whether they&apos;re reading smut.
      </p>
    </article>
  );
}
