export default function TermsPage() {
  return (
    <article className="prose prose-sm max-w-none text-[color:var(--color-ink)]">
      <h1 className="text-2xl font-bold text-[color:var(--color-brand)]">Terms of Service</h1>
      <p>By using IsItSmut, you agree:</p>
      <ul>
        <li>Ratings are generated by AI and are subjective. They may be inaccurate, incomplete, or out of date.</li>
        <li>You will not use this service to defame, harass, or make claims about specific people or copyrighted works.</li>
        <li>We may rate-limit, block, or restrict access at our discretion to prevent abuse.</li>
        <li>The service is provided &quot;as is&quot; with no warranty. We accept no liability for decisions made based on ratings.</li>
        <li>We may change or shut down the service at any time.</li>
      </ul>
      <p>Last updated: 2026-05-17.</p>
    </article>
  );
}
